- Name: combinatorics
  Prefix: cpp
  Display: Combinatorics
  Description: Suite of efficient combinatoric utility functions.

- Name: bin_exp
  Prefix: cpp
  Display: Binary Exponentiation with Modulo
  Description: Effective computation of large exponents module a number.

- Name: ext_euclid_iter
  Prefix: cpp
  Display: Extended Euclidean Algorithm (Iterative)
  Description: Calculates the GCD of A and B while also determining the coefficients for each.

- Name: ext_euclid
  Prefix: cpp
  Display: Extended Euclidean Algorithm
  Description: Calculates the GCD of A and B while also determining the coefficients for each.

- Name: inv_modulo
  Prefix: cpp
  Display: Inverse Modulo
  Description: Returns the modular inverse of a given value using the extended euclidean algorithm.
  Dependencies: [ext_euclid]

- Name: lis
  Prefix: cpp
  Display: Longest Increasing Subsequence
  Description: Given an array of numbers, will return an array containing one of the longest strictly increasing subsequences.

- Name: ostream_overloads
  Prefix: cpp
  Display: Output Stream Overloads
  Description: Set of output stream overloads for common STL containers.
  
- Name: segment_tree
  Prefix: cpp
  Display: Segment Tree
  Description: Construct a segment tree by sum, min, max, or your own combine method.

- Name: sieve_erato
  Prefix: cpp
  Display: Sieve of Eratosthenes
  Description: Find all prime numbers less than or equal to N.

- Name: split_string
  Prefix: cpp
  Display: Split String
  Description: Split a string using a custom delimeter.

- Name: template
  Prefix: cpp
  Display: C++ Template
  Description: A general C++ solution template.

- Name: union_find
  Prefix: cpp
  Display: Union-Find
  Description: Union-find implementation with path compression.